spring:
  application:
    name: eureka-user-provider
  datasource:
    url: jdbc:mysql://192.168.3.29:3306/mydb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://azeroth:8761/eureka/,http://lordaeron:8762/eureka/
server:
  port: 8088
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

