spring:
  application:
    name: feign-user
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://azeroth:8761/eureka/,http://lordaeron:8762/eureka/
    instance:
      prefer-ip-address: true
server:
  port: 8080

feign:
  hystrix:
    enabled: true


